apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: test
  name: test
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: test
    spec:
      containers:
      - image: interviewsregistry.azurecr.io/interviews-server
        name: test
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
